import '@/styles/tailwind/main.css';
import '@/styles/layout/layout.scss';
import 'primeicons/primeicons.css';

import Topbar from "@/components/layout/topbar";
import { Inter } from "next/font/google";
import Menu from '@/components/layout/menu';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PrimeReact",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://primefaces.org/cdn/primereact/images/favicon.ico" rel="icon" type="image/x-icon"></link>
      </head>
      <body className={inter.className}>
        <div className='layout-wrapper layout-light'>
          <Topbar />
            <div className='layout-content'>
              <Menu className='layout-sidebar'/>
              <div className="layout-content-slot">
                {children}
              </div>
          </div>
        </div>
      </body>
    </html>
  );
}
